#
# Update script db version 45 to db version 46
# This creates HA infrastructure in the database
# $Author: heller $
# $Revision: 1.2 $
#
#
#High Availability
#
CREATE TABLE highavail(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,uniqueid VARCHAR(8) NOT NULL UNIQUE,ip VARCHAR(45) NOT NULL,hostname VARCHAR(128) NOT NULL,clientcount INTEGER DEFAULT 0 NOT NULL,operationsystem VARCHAR(128) NOT NULL,productversion VARCHAR(128) NOT NULL,starttime BIGINT NOT NULL,lastupdatetime BIGINT NOT NULL)
CREATE INDEX idx_highavail_uniqueid ON highavail(uniqueid);

