#
# Create a new AS2 CONFIG server database and initialize it
# $Author: heller $
# $Revision: 1.2 $
#
# Create table for update and version control
CREATE TABLE version(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actualversion INTEGER,updatedate TIMESTAMP,updatecomment VARCHAR(255));
#
#Create partner table
CREATE TABLE partner(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,as2ident VARCHAR(255),partnername VARCHAR(255),islocal INTEGER,sign INTEGER,encrypt INTEGER,email VARCHAR(255),url VARCHAR(255),mdnurl VARCHAR(255),msgsubject VARCHAR(255),contenttype VARCHAR(255),syncmdn INTEGER,pollignorelist VARCHAR(1024),pollinterval INTEGER,msgcompression INTEGER,signedmdn INTEGER,usehttpauth INTEGER,httpauthuser VARCHAR(256),httpauthpass VARCHAR(256),usehttpauthasyncmdn INTEGER,httpauthuserasnymdn VARCHAR(256),httpauthpassasnymdn VARCHAR(256),keeporiginalfilenameonreceipt INTEGER,partnercomment OBJECT,notifysend INTEGER,notifyreceive INTEGER,notifysendreceive INTEGER,notifysendenabled INTEGER,notifyreceiveenabled INTEGER,notifysendreceiveenabled INTEGER,contenttransferencoding INTEGER,httpversion VARCHAR(3) DEFAULT '1.1' NOT NULL,maxpollfiles INTEGER DEFAULT 100 NOT NULL,partnercontact OBJECT,partneraddress OBJECT,algidentprotatt INTEGER DEFAULT 1 NOT NULL,enabledirpoll INTEGER DEFAULT 1 NOT NULL);
CREATE INDEX idx_partner_islocal ON partner(islocal);
CREATE INDEX idx_partner_as2ident ON partner(as2ident);
INSERT INTO partner(as2ident,partnername,islocal,sign,encrypt,email,url,mdnurl,msgsubject,contenttype,syncmdn,pollignorelist,pollinterval,msgcompression,signedmdn,usehttpauth,usehttpauthasyncmdn,keeporiginalfilenameonreceipt,notifysend,notifyreceive,notifysendreceive,notifysendenabled,notifyreceiveenabled,notifysendreceiveenabled,contenttransferencoding)VALUES('mycompanyAS2','mycompany',1,2,2,'as2@company.com','http://www.company.com:8080/as2/HttpReceiver','http://www.company.com:8080/as2/HttpReceiver','AS2 message','application/EDI-Consent',1,'*.tmp,*.temp',30,1,1,0,0,0,0,0,0,0,0,0,1);
INSERT INTO partner(as2ident,partnername,islocal,sign,encrypt,email,url,mdnurl,msgsubject,contenttype,syncmdn,pollignorelist,pollinterval,msgcompression,signedmdn,usehttpauth,usehttpauthasyncmdn,keeporiginalfilenameonreceipt,notifysend,notifyreceive,notifysendreceive,notifysendenabled,notifyreceiveenabled,notifysendreceiveenabled,contenttransferencoding)VALUES('mendelsontestAS2','mendelsontest',0,2,2,'as2@mendelson-e-c.com','http://testas2.mendelson-e-c.com:8080/as2/HttpReceiver','http://testas2.mendelson-e-c.com:8080/as2/HttpReceiver','AS2 message','application/EDI-Consent',1,'*.tmp,*.temp',30,1,1,0,0,0,0,0,0,0,0,0,1);
#
#partner events
CREATE TABLE partnerevent(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,partnerid INTEGER,useonreceipt INTEGER DEFAULT 0 NOT NULL,useonsenderror INTEGER DEFAULT 0 NOT NULL,useonsendsuccess INTEGER DEFAULT 0 NOT NULL,typeonreceipt INTEGER DEFAULT 1 NOT NULL,typeonsenderror INTEGER DEFAULT 1 NOT NULL,typeonsendsuccess INTEGER DEFAULT 1 NOT NULL,parameteronreceipt VARCHAR(2048),parameteronsenderror VARCHAR(2048),parameteronsendsuccess VARCHAR(2048),FOREIGN KEY(partnerid)REFERENCES partner(id))
#INSERT INTO partnerevent(parameteronreceipt,parameteronsenderror,parameteronsendsuccess,partnerid)VALUES('c:/mendelson/mbi/SendToMBI.exe -file ${filename} -media as2','C:/mendelson/mbi/SendToLog.exe -tid ${filename} -title "AS2 sending process failed" -details "The AS2 message has NOT been sent:\n${log}" -state ERROR','C:/mendelson/mbi/SendToLog.exe -tid ${filename} -title "AS2 message sent" -details "Success.\nThe AS2 message has been sent:\n${log}" -state SUCCESS',(SELECT id FROM partner WHERE as2ident='mycompanyAS2'))
INSERT INTO partnerevent(parameteronreceipt,parameteronsenderror,parameteronsendsuccess,partnerid)VALUES('YzovbWVuZGVsc29uL21iaS9TZW5kVG9NQkkuZXhlIC1maWxlICR7ZmlsZW5hbWV9IC1tZWRpYSBhczI=','QzovbWVuZGVsc29uL21iaS9TZW5kVG9Mb2cuZXhlIC10aWQgJHtmaWxlbmFtZX0gLXRpdGxlICJBUzIgc2VuZGluZyBwcm9jZXNzIGZhaWxlZCIgLWRldGFpbHMgIlRoZSBBUzIgbWVzc2FnZSBoYXMgTk9UIGJlZW4gc2VudDpcbiR7bG9nfSIgLXN0YXRlIEVSUk9S','QzovbWVuZGVsc29uL21iaS9TZW5kVG9Mb2cuZXhlIC10aWQgJHtmaWxlbmFtZX0gLXRpdGxlICJBUzIgbWVzc2FnZSBzZW50IiAtZGV0YWlscyAiU3VjY2Vzcy5cblRoZSBBUzIgbWVzc2FnZSBoYXMgYmVlbiBzZW50OlxuJHtsb2d9IiAtc3RhdGUgU1VDQ0VTUw==',(SELECT id FROM partner WHERE as2ident='mycompanyAS2'))
#INSERT INTO partnerevent(parameteronreceipt,parameteronsenderror,parameteronsendsuccess,partnerid)VALUES('c:/mendelson/mbi/SendToMBI.exe -file ${filename} -media as2','C:/mendelson/mbi/SendToLog.exe -tid ${filename} -title "AS2 sending process failed" -details "The AS2 message has NOT been sent:\n${log}" -state ERROR','C:/mendelson/mbi/SendToLog.exe -tid ${filename} -title "AS2 message sent" -details "Success.\nThe AS2 message has been sent:\n${log}" -state SUCCESS',(SELECT id FROM partner WHERE as2ident='mendelsontestAS2'))
INSERT INTO partnerevent(parameteronreceipt,parameteronsenderror,parameteronsendsuccess,partnerid)VALUES('YzovbWVuZGVsc29uL21iaS9TZW5kVG9NQkkuZXhlIC1maWxlICR7ZmlsZW5hbWV9IC1tZWRpYSBhczI=','QzovbWVuZGVsc29uL21iaS9TZW5kVG9Mb2cuZXhlIC10aWQgJHtmaWxlbmFtZX0gLXRpdGxlICJBUzIgc2VuZGluZyBwcm9jZXNzIGZhaWxlZCIgLWRldGFpbHMgIlRoZSBBUzIgbWVzc2FnZSBoYXMgTk9UIGJlZW4gc2VudDpcbiR7bG9nfSIgLXN0YXRlIEVSUk9S','QzovbWVuZGVsc29uL21iaS9TZW5kVG9Mb2cuZXhlIC10aWQgJHtmaWxlbmFtZX0gLXRpdGxlICJBUzIgbWVzc2FnZSBzZW50IiAtZGV0YWlscyAiU3VjY2Vzcy5cblRoZSBBUzIgbWVzc2FnZSBoYXMgYmVlbiBzZW50OlxuJHtsb2d9IiAtc3RhdGUgU1VDQ0VTUw==',(SELECT id FROM partner WHERE as2ident='mendelsontestAS2'))
#
#
#notification
CREATE TABLE notification(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,mailhost VARCHAR(255),mailhostport INTEGER,notificationemailaddress VARCHAR(255),notifycertexpire INTEGER DEFAULT 0 NOT NULL,notifytransactionerror INTEGER DEFAULT 0 NOT NULL,notifycem INTEGER DEFAULT 0 NOT NULL,notifysystemfailure INTEGER DEFAULT 0 NOT NULL,notifypostprocessing INTEGER DEFAULT 0 NOT NULL,replyto VARCHAR(255),usesmtpauth INTEGER DEFAULT 0 NOT NULL,smtpauthuser VARCHAR(255),smtpauthpass VARCHAR(255),notifyresend INTEGER DEFAULT 0 NOT NULL,security INTEGER DEFAULT 0 NOT NULL,maxnotificationspermin INTEGER DEFAULT 2 NOT NULL,notifyconnectionproblem INTEGER DEFAULT 0 NOT NULL);
INSERT INTO notification(mailhost,mailhostport,notificationemailaddress,replyto)VALUES('mail.host.de',25,'NotificationReceiver@otherhost.de','DoNotReply@otherhost.de');
#
# additional/modified http headers per partner
CREATE TABLE httpheader(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,partnerid INTEGER,headerkey VARCHAR(255),headervalue VARCHAR(255),FOREIGN KEY(partnerid)REFERENCES partner(id));
#
#certificates and keys go here
CREATE TABLE certificates(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,partnerid INTEGER,fingerprintsha1 VARCHAR(255),category INTEGER,FOREIGN KEY(partnerid)REFERENCES partner(id));
#set encryption cert to key3
INSERT INTO certificates(partnerid,fingerprintsha1,category)VALUES((SELECT id FROM partner WHERE as2ident='mycompanyAS2'),'DC:99:5A:83:60:A4:37:C4:30:3B:10:AC:31:4E:D9:21:16:61:36:77',1);
#set signature cert to key3
INSERT INTO certificates(partnerid,fingerprintsha1,category)VALUES((SELECT id FROM partner WHERE as2ident='mycompanyAS2'),'DC:99:5A:83:60:A4:37:C4:30:3B:10:AC:31:4E:D9:21:16:61:36:77',2);
#set encryption cert to key4
INSERT INTO certificates(partnerid,fingerprintsha1,category)VALUES((SELECT id FROM partner WHERE as2ident='mendelsontestAS2'),'08:FF:33:83:DF:8B:2F:9F:40:BB:F7:88:FE:FD:9C:15:40:E4:FE:C6',1);
#set signature cert to key4
INSERT INTO certificates(partnerid,fingerprintsha1,category)VALUES((SELECT id FROM partner WHERE as2ident='mendelsontestAS2'),'08:FF:33:83:DF:8B:2F:9F:40:BB:F7:88:FE:FD:9C:15:40:E4:FE:C6',2);
#
#information about the partner system
CREATE TABLE partnersystem(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,partnerid INTEGER,as2version VARCHAR(10),productname VARCHAR(255),msgcompression INTEGER DEFAULT 0 NOT NULL,ma INTEGER DEFAULT 0 NOT NULL,cem INTEGER DEFAULT 0 NOT NULL,FOREIGN KEY(partnerid)REFERENCES partner(id));
#
#server settings
CREATE TABLE serversettings(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,vkey VARCHAR(256)NOT NULL,vvalue VARCHAR(256)NOT NULL);
CREATE INDEX idx_serversettings_vkey ON serversettings(vkey);

